"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
type Receipt = { id: number; purchased_at: string; amount: string; status: string; status_label: string; rejection_reason: string };
type Response = { results: Receipt[]; pagination: { page: number; pages: number; has_next: boolean; has_previous: boolean } };
const dateTime = new Intl.DateTimeFormat("ru-RU", { dateStyle: "short", timeStyle: "short" });
const money = new Intl.NumberFormat("ru-RU", { style: "currency", currency: "RUB", maximumFractionDigits: 0 });
function Header() { return <header className="cabinet-header"><Link className="wordmark" href="/">ЧЕК НА УДАЧУ</Link><Link className="back-link" href="/">‹ На сайт</Link><nav className="cabinet-nav" aria-label="Основная навигация"><Link className="nav-link active" href="/cabinet">⌂ Личный кабинет</Link><span className="nav-link">◈ Правила</span><span className="nav-link">♙ Профиль</span></nav><div className="profile-summary"><span className="notification" aria-hidden>♧</span><span className="avatar" aria-hidden>ЕИ</span><span><b>Елена Иванова</b><small>nameuser@email.com</small></span></div></header>; }
export function Cabinet() { const [data, setData] = useState<Response | null>(null), [message, setMessage] = useState("Загружаем чеки…"), [page, setPage] = useState(1), [retry, setRetry] = useState(0); useEffect(() => { let active = true; setMessage("Загружаем чеки…"); fetch(`/api/receipts/?page=${page}`, { credentials: "same-origin" }).then(async (response) => { if (response.status === 401) { window.location.assign("/accounts/login/?next=/cabinet"); return null; } if (!response.ok) throw new Error(); return response.json() as Promise<Response>; }).then((body) => { if (active && body) { setData(body); setMessage(""); } }).catch(() => active && setMessage("Не удалось загрузить чеки.")); return () => { active = false; }; }, [page, retry]); return <main className="cabinet-page"><Header /><section className="history-card" aria-labelledby="history-title"><div className="history-heading"><h1 id="history-title">История чеков</h1><p>Чеков внесено: <b>{data?.results.length ?? 0} шт.</b></p></div>{message && <div className="loading-state" role="status"><span className="loader" aria-hidden />{message}{message.includes("Не удалось") && <button onClick={() => setRetry((value) => value + 1)}>Повторить</button>}</div>}{data?.results.length === 0 && <div className="empty-state"><span className="receipt-illustration" aria-hidden>☷</span><h2>Здесь будет история ваших чеков</h2><p>Вы не добавили еще ни одного чека</p><Link className="button primary-button" href="/">▧ Зарегистрировать чек</Link></div>}{data && data.results.length > 0 && <><div className="receipt-table" role="table"><div className="table-head" role="row"><span>Дата покупки</span><span>Статус</span><span>Сумма чека</span><span>Дата регистрации</span><span>Информация</span></div>{data.results.map((receipt) => <article className="receipt-row" role="row" key={receipt.id}><span className="date-cell"><i aria-hidden>▦</i>{dateTime.format(new Date(receipt.purchased_at))}</span><span><b className={`badge ${receipt.status}`}>{receipt.status_label}</b></span><span>{money.format(Number(receipt.amount))}</span><span>{dateTime.format(new Date(receipt.purchased_at))}</span><span className="receipt-info">{receipt.rejection_reason || (receipt.status === "approved" ? "Чек обработан" : "Чек в обработке")}</span></article>)}</div><div className="history-bottom"><p>ⓘ Иногда проверка вашего чека может занять до 5 рабочих дней</p><Link className="button primary-button" href="/">▧ Зарегистрировать чек</Link></div>{data.pagination.pages > 1 && <nav className="pagination" aria-label="Пагинация чеков"><button disabled={!data.pagination.has_previous} onClick={() => setPage((value) => value - 1)}>‹</button><span>{data.pagination.page} из {data.pagination.pages}</span><button disabled={!data.pagination.has_next} onClick={() => setPage((value) => value + 1)}>›</button></nav>}</>}</section></main>; }
